[package]
name = "u-siem-kernel"
version = "0.0.2"
authors = ["Samuel Garcés <samuel.garces@protonmail.com>"]
license = "MIT"
description = "Library to be used to build a custom SIEM with the framework uSIEM"
repository = "https://github.com/u-siem/usiem-kernel"
keywords = ["SIEM", "security", "logs"]
categories = ["security"]
edition = "2018"

[lib]
name = "usiem_kernel"
path = "src/lib.rs"

[features]
metrics = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
u-siem = { version = "0.0" }
chrono = "0.4"
crossbeam-channel = { version = "0.5"}
serde_json = "1.0"
prometheus = "0.13"
lazy_static = "1.4"